name: core
description: Core
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  model:
    path: model
  client:
    path: client
  client_impl:
    path: client_impl
  repository:
    path: repository
  repository_impl:
    path: repository_impl
  service:
    path: service
  service_impl:
    path: service_impl

dev_dependencies:
  flutter_test:
    sdk: flutter
